//! Goal 226: `rpg init` interactive project wizard.
//!
//! Interactive CLI that asks about project requirements (web? desktop? mobile?
//! SSR? SSG?) and generates the optimal project configuration.

use std::collections::HashMap;

/// A project template.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProjectTemplate {
    /// Web-only app.
    Web,
    /// Desktop app (Tauri/Wry).
    Desktop,
    /// Mobile app.
    Mobile,
    /// Full-stack with SSR.
    Ssr,
    /// Static site generation.
    Ssg,
    /// Library / component library.
    Library,
    /// Monorepo.
    Monorepo,
}

impl ProjectTemplate {
    /// Get the display name.
    pub fn display_name(&self) -> &'static str {
        match self {
            ProjectTemplate::Web => "Web App",
            ProjectTemplate::Desktop => "Desktop App",
            ProjectTemplate::Mobile => "Mobile App",
            ProjectTemplate::Ssr => "Full-Stack (SSR)",
            ProjectTemplate::Ssg => "Static Site (SSG)",
            ProjectTemplate::Library => "Component Library",
            ProjectTemplate::Monorepo => "Monorepo",
        }
    }

    /// Get the recommended features.
    pub fn recommended_features(&self) -> Vec<&'static str> {
        match self {
            ProjectTemplate::Web => vec!["hydration", "code-split", "pwa"],
            ProjectTemplate::Desktop => vec!["native-renderer", "windowing", "file-system"],
            ProjectTemplate::Mobile => vec!["native-modules", "push-notifications", "biometric"],
            ProjectTemplate::Ssr => vec!["ssr", "streaming", "server-actions", "hydration"],
            ProjectTemplate::Ssg => vec!["ssg", "prerender", "static-assets"],
            ProjectTemplate::Library => vec!["component-registry", "docs"],
            ProjectTemplate::Monorepo => vec!["workspace", "shared-deps", "cross-imports"],
        }
    }

    /// Get the recommended dependencies.
    pub fn recommended_deps(&self) -> Vec<&'static str> {
        match self {
            ProjectTemplate::Web => vec!["rye-core", "rye-html", "rye-router"],
            ProjectTemplate::Desktop => vec!["rye-core", "rye-desktop", "rye-router"],
            ProjectTemplate::Mobile => vec!["rye-core", "rye-mobile", "rye-router"],
            ProjectTemplate::Ssr => vec!["rye-core", "rye-ssr", "rye-router", "rye-db"],
            ProjectTemplate::Ssg => vec!["rye-core", "rye-ssr", "rye-router"],
            ProjectTemplate::Library => vec!["rye-core", "rye-macros"],
            ProjectTemplate::Monorepo => vec!["rye-core", "rye-router", "rye-cli"],
        }
    }
}

/// A wizard question.
#[derive(Debug, Clone)]
pub struct WizardQuestion {
    /// The question text.
    pub question: String,
    /// The options.
    pub options: Vec<String>,
    /// The default option index.
    pub default: usize,
}

impl WizardQuestion {
    /// Create a new question.
    pub fn new(question: &str, options: Vec<&str>, default: usize) -> Self {
        Self {
            question: question.to_string(),
            options: options.iter().map(|s| s.to_string()).collect(),
            default,
        }
    }
}

/// The project configuration generated by the wizard.
#[derive(Debug, Clone)]
pub struct ProjectConfig {
    /// The project name.
    pub name: String,
    /// The project template.
    pub template: ProjectTemplate,
    /// The selected features.
    pub features: Vec<String>,
    /// The dependencies.
    pub dependencies: Vec<String>,
    /// Whether to use TypeScript-style types.
    pub use_strict_types: bool,
    /// Whether to generate tests.
    pub generate_tests: bool,
    /// Whether to set up CI/CD.
    pub setup_ci: bool,
}

impl ProjectConfig {
    /// Create a new config from a template.
    pub fn from_template(name: &str, template: ProjectTemplate) -> Self {
        Self {
            name: name.to_string(),
            template,
            features: template
                .recommended_features()
                .iter()
                .map(|s| s.to_string())
                .collect(),
            dependencies: template
                .recommended_deps()
                .iter()
                .map(|s| s.to_string())
                .collect(),
            use_strict_types: true,
            generate_tests: true,
            setup_ci: false,
        }
    }

    /// Generate the Cargo.toml content.
    pub fn generate_cargo_toml(&self) -> String {
        let mut toml = String::new();
        toml.push_str("[package]\n");
        toml.push_str(&format!("name = \"{}\"\n", self.name));
        toml.push_str("version = \"0.1.0\"\n");
        toml.push_str("edition = \"2021\"\n\n");
        toml.push_str("[dependencies]\n");
        for dep in &self.dependencies {
            toml.push_str(&format!("{} = \"*\"\n", dep));
        }
        toml
    }

    /// Generate the project structure.
    pub fn generate_structure(&self) -> Vec<String> {
        let mut paths = vec![
            "src/".to_string(),
            "src/main.rs".to_string(),
            "src/app.rs".to_string(),
            "src/components/".to_string(),
            "src/components/mod.rs".to_string(),
        ];

        if self.template == ProjectTemplate::Ssr || self.template == ProjectTemplate::Ssg {
            paths.push("src/pages/".to_string());
            paths.push("src/pages/mod.rs".to_string());
        }

        if self.generate_tests {
            paths.push("tests/".to_string());
            paths.push("tests/integration.rs".to_string());
        }

        if self.setup_ci {
            paths.push(".github/workflows/ci.yml".to_string());
        }

        paths
    }
}

/// The interactive project wizard.
pub struct ProjectWizard {
    questions: Vec<WizardQuestion>,
}

impl ProjectWizard {
    /// Create a new wizard with default questions.
    pub fn new() -> Self {
        Self {
            questions: vec![
                WizardQuestion::new(
                    "What type of project?",
                    vec![
                        "web", "desktop", "mobile", "ssr", "ssg", "library", "monorepo",
                    ],
                    0,
                ),
                WizardQuestion::new("Generate tests?", vec!["yes", "no"], 0),
                WizardQuestion::new("Set up CI/CD?", vec!["yes", "no"], 1),
            ],
        }
    }

    /// Get the questions.
    pub fn questions(&self) -> &[WizardQuestion] {
        &self.questions
    }

    /// Generate a config from answers.
    pub fn generate_config(&self, name: &str, answers: &[usize]) -> ProjectConfig {
        let template = match answers.first().copied().unwrap_or(0) {
            0 => ProjectTemplate::Web,
            1 => ProjectTemplate::Desktop,
            2 => ProjectTemplate::Mobile,
            3 => ProjectTemplate::Ssr,
            4 => ProjectTemplate::Ssg,
            5 => ProjectTemplate::Library,
            6 => ProjectTemplate::Monorepo,
            _ => ProjectTemplate::Web,
        };

        let generate_tests = answers.get(1).copied().unwrap_or(0) == 0;
        let setup_ci = answers.get(2).copied().unwrap_or(1) == 0;

        let mut config = ProjectConfig::from_template(name, template);
        config.generate_tests = generate_tests;
        config.setup_ci = setup_ci;
        config
    }
}

impl Default for ProjectWizard {
    fn default() -> Self {
        Self::new()
    }
}

/// Run the init command.
pub fn run(args: &[String]) {
    let name = args
        .iter()
        .find(|a| !a.starts_with("--"))
        .map(|s| s.as_str())
        .unwrap_or("my-app");
    let template = args
        .iter()
        .find(|a| a.starts_with("--template"))
        .map(|a| &a[10..])
        .unwrap_or("web");

    let proj_template = match template {
        "desktop" => ProjectTemplate::Desktop,
        "mobile" => ProjectTemplate::Mobile,
        "ssr" => ProjectTemplate::Ssr,
        "ssg" => ProjectTemplate::Ssg,
        "library" => ProjectTemplate::Library,
        "monorepo" => ProjectTemplate::Monorepo,
        _ => ProjectTemplate::Web,
    };

    let config = ProjectConfig::from_template(name, proj_template);
    println!(
        "Creating project: {} ({})",
        config.name,
        config.template.display_name()
    );
    println!("Features: {}", config.features.join(", "));
    println!("Dependencies: {}", config.dependencies.join(", "));
    println!("\nProject structure:");
    for path in config.generate_structure() {
        println!("  {}", path);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_project_template_display_name() {
        assert_eq!(ProjectTemplate::Web.display_name(), "Web App");
        assert_eq!(ProjectTemplate::Ssr.display_name(), "Full-Stack (SSR)");
    }

    #[test]
    fn test_project_template_recommended_features() {
        let features = ProjectTemplate::Web.recommended_features();
        assert!(features.contains(&"hydration"));
        assert!(features.contains(&"code-split"));
    }

    #[test]
    fn test_project_template_recommended_deps() {
        let deps = ProjectTemplate::Ssr.recommended_deps();
        assert!(deps.contains(&"rye-ssr"));
        assert!(deps.contains(&"rye-db"));
    }

    #[test]
    fn test_project_config_from_template() {
        let config = ProjectConfig::from_template("my-app", ProjectTemplate::Web);
        assert_eq!(config.name, "my-app");
        assert!(!config.features.is_empty());
        assert!(!config.dependencies.is_empty());
    }

    #[test]
    fn test_project_config_generate_cargo_toml() {
        let config = ProjectConfig::from_template("my-app", ProjectTemplate::Web);
        let toml = config.generate_cargo_toml();
        assert!(toml.contains("[package]"));
        assert!(toml.contains("my-app"));
        assert!(toml.contains("rye-core"));
    }

    #[test]
    fn test_project_config_generate_structure() {
        let config = ProjectConfig::from_template("my-app", ProjectTemplate::Web);
        let paths = config.generate_structure();
        assert!(paths.contains(&"src/main.rs".to_string()));
        assert!(paths.contains(&"src/components/".to_string()));
    }

    #[test]
    fn test_project_config_generate_structure_ssr() {
        let config = ProjectConfig::from_template("my-app", ProjectTemplate::Ssr);
        let paths = config.generate_structure();
        assert!(paths.contains(&"src/pages/".to_string()));
    }

    #[test]
    fn test_project_config_generate_structure_with_ci() {
        let mut config = ProjectConfig::from_template("my-app", ProjectTemplate::Web);
        config.setup_ci = true;
        let paths = config.generate_structure();
        assert!(paths.contains(&".github/workflows/ci.yml".to_string()));
    }

    #[test]
    fn test_wizard_new() {
        let wizard = ProjectWizard::new();
        assert!(!wizard.questions().is_empty());
    }

    #[test]
    fn test_wizard_generate_config_web() {
        let wizard = ProjectWizard::new();
        let config = wizard.generate_config("test", &[0, 0, 1]);
        assert_eq!(config.template, ProjectTemplate::Web);
        assert!(config.generate_tests);
        assert!(!config.setup_ci);
    }

    #[test]
    fn test_wizard_generate_config_ssr() {
        let wizard = ProjectWizard::new();
        let config = wizard.generate_config("test", &[3, 1, 0]);
        assert_eq!(config.template, ProjectTemplate::Ssr);
        assert!(!config.generate_tests);
        assert!(config.setup_ci);
    }
}
