//! Bindings generator — produces Kotlin (Android) and Swift (iOS) files
//! that call the FFI functions exposed by the `jni` and `objc` modules.
//!
//! ## Usage
//! ```no_run
//! use rye_mobile::ffi::bindings_gen;
//!
//! let kotlin = bindings_gen::generate_kotlin_bindings();
//! let swift = bindings_gen::generate_swift_bindings();
//! std::fs::write("RyeNative.kt", kotlin).unwrap();
//! std::fs::write("RyeNative.swift", swift).unwrap();
//! ```

/// Generate the Kotlin bindings file for Android.
///
/// Produces a `RyeNative.kt` file with `external` JNI method declarations
/// and a companion object for managing the native bridge.
pub fn generate_kotlin_bindings() -> String {
    r#"// Auto-generated by rye-mobile FFI bindings generator.
// Do not edit manually — regenerate with `cargo run -p rye-mobile --bin gen-bindings`.

package rye

import android.view.Surface

/**
 * Native bridge for the rye UI framework.
 *
 * This class provides JNI bindings to the Rust rye-mobile library.
 * All methods are `external` and delegate to the native Rust code.
 */
class RyeNative {
    companion object {
        init {
            System.loadLibrary("rye_mobile")
        }

        // Lifecycle

        /** Initialize the native renderer. Returns a bridge pointer (0 on failure). */
        external fun nativeInit(width: Int, height: Int, scale: Float, surface: Long): Long

        /** Destroy the native renderer and free resources. */
        external fun nativeDestroy(bridgePtr: Long)

        // Element / Text creation

        /** Create a new element with the given tag. Returns an element handle. */
        external fun createElement(bridgePtr: Long, tag: String): Long

        /** Create a new text node with the given content. Returns a text handle. */
        external fun createText(bridgePtr: Long, content: String): Long

        // Mutations

        /** Set the text content of a text node. */
        external fun setText(bridgePtr: Long, textHandle: Long, content: String)

        /** Set an attribute on an element. */
        external fun setAttribute(bridgePtr: Long, elementHandle: Long, name: String, value: String)

        /** Remove an attribute from an element. */
        external fun removeAttribute(bridgePtr: Long, elementHandle: Long, name: String)

        /** Insert a child node at the given index. */
        external fun insertChild(
            bridgePtr: Long,
            parentHandle: Long,
            childHandle: Long,
            childIsElement: Int,
            index: Int
        )

        /** Remove the child at the given index. */
        external fun removeChild(bridgePtr: Long, parentHandle: Long, index: Int)

        /** Replace the child at the given index with a new node. */
        external fun replaceChild(
            bridgePtr: Long,
            parentHandle: Long,
            childHandle: Long,
            childIsElement: Int,
            index: Int
        )

        /** Move a child from one index to another. */
        external fun moveChild(bridgePtr: Long, parentHandle: Long, from: Int, to: Int)

        // Rendering

        /** Request a redraw of the rendering surface. */
        external fun requestRedraw(bridgePtr: Long)

        /** Get the number of created elements (for testing). */
        external fun elementCount(bridgePtr: Long): Int
    }
}
"#.to_string()
}

/// Generate the Swift bindings file for iOS.
///
/// Produces a `RyeNative.swift` file with C function declarations
/// and a Swift class that wraps the C ABI.
pub fn generate_swift_bindings() -> String {
    r#"// Auto-generated by rye-mobile FFI bindings generator.
// Do not edit manually — regenerate with `cargo run -p rye-mobile --bin gen-bindings`.

import Foundation
import UIKit

// C ABI declarations
@_silgen_name("rye_native_init")
func rye_native_init(_ width: UInt32, _ height: UInt32, _ scale: Float, _ surface: UnsafeMutableRawPointer) -> OpaquePointer?

@_silgen_name("rye_native_destroy")
func rye_native_destroy(_ bridge: OpaquePointer?)

@_silgen_name("rye_create_element")
func rye_create_element(_ bridge: OpaquePointer?, _ tag: UnsafePointer<CChar>) -> Int64

@_silgen_name("rye_create_text")
func rye_create_text(_ bridge: OpaquePointer?, _ content: UnsafePointer<CChar>) -> Int64

@_silgen_name("rye_set_text")
func rye_set_text(_ bridge: OpaquePointer?, _ textHandle: Int64, _ content: UnsafePointer<CChar>)

@_silgen_name("rye_set_attribute")
func rye_set_attribute(_ bridge: OpaquePointer?, _ elementHandle: Int64, _ name: UnsafePointer<CChar>, _ value: UnsafePointer<CChar>)

@_silgen_name("rye_remove_attribute")
func rye_remove_attribute(_ bridge: OpaquePointer?, _ elementHandle: Int64, _ name: UnsafePointer<CChar>)

@_silgen_name("rye_insert_child")
func rye_insert_child(_ bridge: OpaquePointer?, _ parentHandle: Int64, _ childHandle: Int64, _ childIsElement: Int32, _ index: Int32)

@_silgen_name("rye_remove_child")
func rye_remove_child(_ bridge: OpaquePointer?, _ parentHandle: Int64, _ index: Int32)

@_silgen_name("rye_replace_child")
func rye_replace_child(_ bridge: OpaquePointer?, _ parentHandle: Int64, _ childHandle: Int64, _ childIsElement: Int32, _ index: Int32)

@_silgen_name("rye_move_child")
func rye_move_child(_ bridge: OpaquePointer?, _ parentHandle: Int64, _ from: Int32, _ to: Int32)

@_silgen_name("rye_request_redraw")
func rye_request_redraw(_ bridge: OpaquePointer?)

@_silgen_name("rye_element_count")
func rye_element_count(_ bridge: OpaquePointer?) -> Int32

/// Native bridge for the rye UI framework.
///
/// This class wraps the C ABI to the Rust rye-mobile library.
class RyeNative {
    private let bridge: OpaquePointer

    /// Initialize the native renderer with a UIView's layer.
    init(width: UInt32, height: UInt32, scale: Float, surface: UnsafeMutableRawPointer) {
        guard let ptr = rye_native_init(width, height, scale, surface) else {
            fatalError("Failed to initialize rye native renderer")
        }
        self.bridge = ptr
    }

    deinit {
        rye_native_destroy(bridge)
    }

    // Element / Text creation

    /// Create a new element with the given tag.
    func createElement(_ tag: String) -> Int64 {
        return tag.withCString { ptr in
            rye_create_element(bridge, ptr)
        }
    }

    /// Create a new text node with the given content.
    func createText(_ content: String) -> Int64 {
        return content.withCString { ptr in
            rye_create_text(bridge, ptr)
        }
    }

    // Mutations

    /// Set the text content of a text node.
    func setText(_ textHandle: Int64, _ content: String) {
        content.withCString { ptr in
            rye_set_text(bridge, textHandle, ptr)
        }
    }

    /// Set an attribute on an element.
    func setAttribute(_ elementHandle: Int64, _ name: String, _ value: String) {
        name.withCString { namePtr in
            value.withCString { valuePtr in
                rye_set_attribute(bridge, elementHandle, namePtr, valuePtr)
            }
        }
    }

    /// Remove an attribute from an element.
    func removeAttribute(_ elementHandle: Int64, _ name: String) {
        name.withCString { ptr in
            rye_remove_attribute(bridge, elementHandle, ptr)
        }
    }

    /// Insert a child node at the given index.
    func insertChild(_ parentHandle: Int64, _ childHandle: Int64, isElement: Bool, index: Int32) {
        rye_insert_child(bridge, parentHandle, childHandle, isElement ? 1 : 0, index)
    }

    /// Remove the child at the given index.
    func removeChild(_ parentHandle: Int64, _ index: Int32) {
        rye_remove_child(bridge, parentHandle, index)
    }

    /// Replace the child at the given index with a new node.
    func replaceChild(_ parentHandle: Int64, _ childHandle: Int64, isElement: Bool, index: Int32) {
        rye_replace_child(bridge, parentHandle, childHandle, isElement ? 1 : 0, index)
    }

    /// Move a child from one index to another.
    func moveChild(_ parentHandle: Int64, from: Int32, to: Int32) {
        rye_move_child(bridge, parentHandle, from, to)
    }

    // Rendering

    /// Request a redraw of the rendering surface.
    func requestRedraw() {
        rye_request_redraw(bridge)
    }

    /// Get the number of created elements (for testing).
    var elementCount: Int32 {
        return rye_element_count(bridge)
    }
}
"#.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_kotlin_bindings() {
        let code = generate_kotlin_bindings();
        assert!(code.contains("package rye"));
        assert!(code.contains("external fun nativeInit"));
        assert!(code.contains("external fun createElement"));
        assert!(code.contains("external fun setAttribute"));
        assert!(code.contains("external fun insertChild"));
        assert!(code.contains("external fun requestRedraw"));
        assert!(code.contains("System.loadLibrary"));
    }

    #[test]
    fn test_generate_swift_bindings() {
        let code = generate_swift_bindings();
        assert!(code.contains("@_silgen_name"));
        assert!(code.contains("rye_native_init"));
        assert!(code.contains("rye_create_element"));
        assert!(code.contains("rye_set_attribute"));
        assert!(code.contains("rye_insert_child"));
        assert!(code.contains("rye_request_redraw"));
        assert!(code.contains("class RyeNative"));
        assert!(code.contains("OpaquePointer"));
    }
}
